services:
  database:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    networks:
      - app
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "main"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  app:
    driver: bridge

volumes:
  db_data:

  redisdata:
