services:
  database:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    networks:
      - app
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  app:
    driver: bridge

volumes:
  db_data:
